/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dat250assignment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void testUnitConversion(){
        assertEquals(0.0254, App.convertUnit(1, "in", "m"));
        assertEquals(0, App.convertUnit(0, "in", "m"));
        assertEquals(0, App.convertUnit(0,"ft", "mi"));

    }
}
